clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true
pipeline:
  test:
    image: golang:1.19-alpine
    commands:
      - go test ./... -race

  release:
    image: goreleaser/goreleaser
    secrets: [gh_api_key]
    commands:
      - goreleaser release
    when:
      event: tag
