clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      tags: true
pipeline:
  #test:
  #  image: golang:1.19-alpine
  #  commands:
  #    - go test ./...

  release:
    image: goreleaser/goreleaser
    secrets:
     - source: gh_api_key
       target: GITHUB_TOKEN
    commands:
      - goreleaser release
    when:
      event: tag
